services:
  - type: web
    name: grow-tenders-backend
    runtime: node
    region: singapore
    plan: free

    buildCommand: npm ci && npx puppeteer browsers install chrome && npx prisma generate && npm run build


    startCommand: npm run start:prod

    envVars:
      - key: NODE_ENV
        value: production

      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/src/.cache/puppeteer

      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false

    healthCheckPath: /api
