services:
  - type: web
    name: grow-tenders-backend
    runtime: node
    region: singapore
    plan: free
    buildCommand: npm install --legacy-peer-deps --include=dev && node_modules/.bin/prisma generate && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/src/.cache/puppeteer
    healthCheckPath: /api
